//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VidChat.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.callInfoes = new HashSet<callInfo>();
        }
    
        public System.Guid UserId { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string LastName_ { get; set; }
        public string FirstName { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<System.DateTime> LogInTime { get; set; }
        public Nullable<System.DateTime> LogOutTime { get; set; }
    
        public virtual callInfo callInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<callInfo> callInfoes { get; set; }
        public virtual role role { get; set; }
    }
}
