language: csharp
solution: OpenTok.sln
install:
  - nuget restore OpenTok.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release OpenTok.sln
  - mono --runtime=v4.0 ./testrunner/xunit.runners.1.9.2/tools/xunit.console.exe ./OpenTokTest/bin/Release/OpenTokTest.dll